/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecretLocationRouteImport } from './routes/secret-location'
import { Route as PortfolioRouteImport } from './routes/portfolio'

const SecretLocationRoute = SecretLocationRouteImport.update({
  id: '/secret-location',
  path: '/secret-location',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/portfolio': typeof PortfolioRoute
  '/secret-location': typeof SecretLocationRoute
}
export interface FileRoutesByTo {
  '/portfolio': typeof PortfolioRoute
  '/secret-location': typeof SecretLocationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/portfolio': typeof PortfolioRoute
  '/secret-location': typeof SecretLocationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/portfolio' | '/secret-location'
  fileRoutesByTo: FileRoutesByTo
  to: '/portfolio' | '/secret-location'
  id: '__root__' | '/portfolio' | '/secret-location'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PortfolioRoute: typeof PortfolioRoute
  SecretLocationRoute: typeof SecretLocationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/secret-location': {
      id: '/secret-location'
      path: '/secret-location'
      fullPath: '/secret-location'
      preLoaderRoute: typeof SecretLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PortfolioRoute: PortfolioRoute,
  SecretLocationRoute: SecretLocationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
